name: Update file on PR merge
on:
  pull_request:
    branches:
      - master
      - develop
    types: closed

jobs:
  update_date:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch with full history
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update time.txt
        run: |
          date > time.txt

      - name: Amend the last commit
        run: |
          git config --global user.email "gitbot@openrct2.org"
          git config --global user.name "OpenRCT2 git bot"
          git add time.txt
          git commit --amend --no-edit
          git push --force-with-lease
          echo "Complete"
